### ISSUE TITLE
Code seems to be incompatible with 4.2?

### ISSUE THREAD

**Issue by Oochiiehehe3** [michaelgundlach/rhythm_notifier#1]
Hi! I'm currently attempting to start making a rhythm game, and I wasn't sure what to do until I found this addon. It seemed perfect for the project, but I ran into a couple issues. First of all, when I downloaded the files, there was a line in the code that gave an error immediately. On line 219, in the ready function, it says, "`beats(1.0).connect(beat.emit)`," which gets highlighted in red and gives these errors:
`res://addons/rhythm_notifier/rhythm_notifier.gd:219 - Parse Error: Cannot find property "emit" on base "Signal".`
`res://addons/rhythm_notifier/rhythm_notifier.gd:219 - Parse Error: Cannot find member "emit" in base "Signal".`

I attempted to fix these errors by creating this function:

`func emit_beat():`
`      beat.emit()`

and calling that in the line instead:

`beats(1.0).connect(emit_beat)`

However, while this did get rid of the error messages, the RhythmNotifier Node did not appear in the Node list when I tried to add it. I am using Godot version 4.2.2, and while I am aware that many plugins don't work on 4.2, you seem to have created this addon within the last month, so I would assume that it works with the current version.

Please let me know if I did something wrong or if there is some way to fix this problem. Thank you!

**Comment by michaelgundlach** [comment]
Hi! I tested this on 4.3, which is the latest stable version. If you're just getting started, I recommend using 4.3.  But thanks for letting me know about the problems - I'd like this addon to work on 4.0+, so I'll track both of these issues down.

**Comment by Oochiiehehe3** [comment]
Oh! I didn't realize I was still running an older version of Godot! I knew I thought I remembered 4.3 being out. Anyway, I downloaded 4.3 and it seems to work fine now. Thanks for your help!

**Comment by michaelgundlach** [comment]
Sure thing, please feel free to file any requests for features or suggestions that you have!

**Comment by michaelgundlach** [comment]
@Oochiiehehe3 Can you confirm that in 4.3, the RhythmNotifier node appears in the Create New Node dialog?

**Comment by Oochiiehehe3** [comment]
@michaelgundlach yes, it appeared and I was able to use it to create a basic movement system.

**Comment by Oochiiehehe3** [comment]
Hey just wanted to check, you said, “feel free to file requests/suggestions,” and I’m not sure where exactly I would do that if I wanted to.

**Comment by michaelgundlach** [comment]
Right here on GitHub - just open an issue :)
